#!/bin/bash

# Automatically referencing commits in Asana tasks.
#
# -----------------------
# necessary configuration:
# git config --global user.asana-token "MY_ASANA_PERSONAL_ACCESS_TOKEN" (http://app.asana.com/-/account_api)
# -----------------------

access_token=$(git config user.asana-token)

if [ $access_token == "" ]; then
    echo "[post-commit] Set Asana Token git config --global user.asana-token \"MY_ASANA_PERSONAL_ACCESS_TOKEN\" (http://app.asana.com/-/account_api)" >&2
    exit 1
fi

remote=$(git remote -v)

project_pattern="\(fetch\).*git@bitbucket.org:(.*).git \(push\)"
if [[ $remote =~ $project_pattern ]]; then
  project=${BASH_REMATCH[1]}
else
  echo "[post-commit] Unable to find Bitbucket project"
  exit 1
fi

hash=$(git rev-parse HEAD)

commit_url="https://bitbucket.org/$project/commits/$hash"

print_comment="Committed $commit_url"

comment=$(git log --pretty=format:"%B" -n1 | tr '\n' ' ')

IFS=' ' read -a words <<< "$comment"

taskid_pattern="https://app\.asana\.com/0/[0-9]+/([0-9]+)"

for element in "${words[@]}"
do
    if [[ $element =~ $taskid_pattern ]]; then
      echo "[post-commit] Adding commit comment to Asana" >&2
        curl \
          -H "Authorization: Bearer ${access_token}" \
          -X POST \
          --data-urlencode "html_text=${print_comment}" \
          "https://app.asana.com/api/1.0/tasks/${BASH_REMATCH[1]}/stories" \
          > /dev/null 2>&1
    fi
done
